name: Core Banking API - CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: JDK 21 Configuration
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Maven Wrapper Permissions
        run: chmod +x ./mvnw

      - name: Run Tests
        run: ./mvnw test

      - name: Build Project
        run: ./mvnw clean package -DskipTests